name: flutter_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_js: ^0.8.1
  google_generative_ai: ^0.4.6
  firebase_core: ^3.8.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.3
  speech_to_text: ^7.0.0
  tflite: ^1.1.2
  image_picker: ^0.8.7+4
  image: ^3.0.1
  tflite_flutter: ^0.9.0
  http: ^1.2.2
  file_picker: ^5.2.3
  path_provider: ^2.0.11
  http_parser: ^4.0.0
  flutter_dotenv: ^5.0.2
  fl_chart: 0.36.0  # A more stable version that might not have this issue.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/models/cnn_model.tflite
      - assets/models/ann_model.tflite
      - assets/images/download.jpeg
